project:
  type: book

book:
  title: "IRAS Research Data Management Guidelines"
  author:
    - "Inka Pieterson"
    - "Marthe Knijff"
    - "Zimbo Boudewijns"
  date: last-modified
  # cover-image: fig/uu-logo-en-geenwitruimte.png
  search: true
  sidebar:
    collapse-level: 1
    logo: fig/uu-logo-en-geenwitruimte.png

  chapters:
    - index.qmd
    
    - part: intro.qmd
      chapters:
      - intro_structure.qmd
      - intro_importance.qmd
      - intro_responsibilities.qmd
      - intro_support.qmd
      
    - part: planning.qmd
      chapters:
      - planning_dmp.qmd
      - planning_costs.qmd
      
    - part: during.qmd
      chapters:
      - during_collecting.qmd
      - during_storing.qmd
      - during_documenting.qmd
      - during_analyzing.qmd
      
    - part: after.qmd
      chapters:
      - after_archiving.qmd
      - after_publishing.qmd
      
    - part: privacy.qmd
      chapters:
      - privacy_legislation.qmd
      - privacy_personal.qmd
      - privacy_security.qmd
      - privacy_....qmd
      
    - references.qmd
    - appendix_a.qmd
    - appendix_b.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '(quarto_book|iras-data-guidelines|pages\.github\.io)' #check how to filter external links exactly so they get an icon and automatically open in a new window
  pdf:
    documentclass: scrreprt

editor: visual

