# Collecting data {#sec-during_collecting}

## Formdesk

...

## Informed consent

...

<!--# Is in de meeste gevallen wel nodig, misschien hier kort iets erover zeggen en verwijzen naar hoodstuk over privacy? -->

## Qualtrics

If you want to create a survey that will collect personal data, the UU has one option and that is Qualtrics. Qualtrics is free of charge and can be used to set up surveys, collect data, distribute and analyze responses. Issues such as privacy and security are well taken care of. For further information please refer to the [Qualtrics intranet page](https://intranet.uu.nl/en/knowledgebase/qualtrics-a-survey-tool) of the UU. It tells more about privacy, rules of conduct, non-standard UU modules in Qualtrics and more.

You can log into the [Qualtrics website](https://survey.uu.nl/) with your Solis-id (or UU email address), Solis-password and two-factor authentication. Once you have logged into Qualtrics, you can [create a new survey](https://www.qualtrics.com/support/survey-platform/my-projects/my-projects-overview/#CreatingNewProjects) via the Projects page. The Project page shows all surveys you have created (or that have been shared with you). You can collaborate on surveys with others by [sharing](https://www.qualtrics.com/support/survey-platform/my-projects/my-projects-overview/#Sharing) them.

[Appendix B](appendix_b.qmd) offers recommendations and tips and tricks for building a Qualtrics survey in a FAIR and structured way, while keeping data quality and privacy in mind. This may take some investment upfront, but will pay off in the end.

<!--# Moet misschien nog aangevuld worden a.d.h.v. Inka's opmerking in document op Teams met opzet voor Qualtrics-document. -->
