# Preface {.unnumbered}

This book serves as a guideline for research data management at the [Institute for Risk Assessment Sciences (IRAS)](https://www.uu.nl/en/organisation/faculty-of-veterinary-medicine/about-the-faculty/organisation/department-population-health-sciences/institute-for-risk-assessment-sciences-iras) of the Faculty of Veterinary Science. It outlines and defines a set of principles regarding research data and provides practical handlers for researchers in accordance with the regulations established in the [University Policy Framework for Research Data from Utrecht University (UU)](https://www.uu.nl/sites/default/files/university_policy_framework_for_research_data_utrecht_university_-_january_2016.pdf) and the [Research Data Management Guidelines developed by the Faculty of Veterinary Medicine](https://solisservices.sharepoint.com/:b:/s/WerkgroepRDM/IQCjzf0aKi-uS7x3TiG66yMoAWXuSrgG5IFlhtxLPUBkokE?e=5vHGXI&xsdata=MDV8MDJ8bS5rbmlqZmZAdXUubmx8NzYzM2EzZmQ2OGRlNGRmNDkxN2YwOGRlOTYyZTVkNmR8ZDcyNzU4YTBhNDQ2NGUwZmEwYWE0YmY5NWE0YTEwZTd8MHwwfDYzOTExMzMyMzAzMTUxMzczNnxVbmtub3dufFRXRnBiR1pzYjNkOGV5SkZiWEIwZVUxaGNHa2lPblJ5ZFdVc0lsWWlPaUl3TGpBdU1EQXdNQ0lzSWxBaU9pSlhhVzR6TWlJc0lrRk9Jam9pVFdGcGJDSXNJbGRVSWpveWZRPT18MHx8fA%3d%3d&sdata=eEh1c1o2WnBNZkJlQUQwL2JNSktjTVZBcWo0VVQ1VDNkd1lpYTdNZXRMWT0%3d). These guidelines can be used as a reference together with existing UU policies, faculty guidelines and/or procedures already established by research groups.

::: {.callout-important}

Please note that the [UU’s University Policy Framework for Research Data](https://www.uu.nl/sites/default/files/university_policy_framework_for_research_data_utrecht_university_-_january_2016.pdf) dates back to 1 January 2016. This is before e.g. the GDPR was established. Hence, some of the information mentioned in the policy framework is not up to date. UU is in the process of creating a new policy framework. In the meantime, please consult [RDM Support](mailto:info.rdm@uu.nl) in case of doubt about the information in the current policy framework.

:::