# Support {#sec-intro_support}

## IRAS Data Management team {#sec-intro_support_iras}

The IRAS Data Management team is available for consultation on matters related to data management. We have a wide variety of expertise within the team, from data collection and cleaning to working with GIS data and setting up and hosting applications. While capacity within the team is limited when it comes to providing hands-on support, we will most of the time be able to provide advice on any data related questions you might have or bring you in to contact with the right people to help you further.

<!--# Hier ook document met DM-services opnemen. Geldt wel alleen voor OHC (dit hier benoemen), maar misschien dat de andere afdelingen soortgelijke documenten kunnen opstellen. -->

::: callout-note
### IRAS Data Management team

Data management representatives:

-   **Coordinator**: Zimbo Boudewijns
-   **One Health Chemical (OHC) representatives**: Inka Pieterson, Marthe Knijff ([iras_dm\@uu.nl](mailto:iras_dm@uu.nl))
-   **One Health Microbial (OHM) representative:** Peter Scherpenisse ([p.scherpenisse\@uu.nl](mailto:p.scherpenisse@uu.nl))
-   **One Health Toxicology (OHT) representative:** Kas Adriaans ([k.j.adriaans\@uu.nl](mailto:k.j.adriaans@uu.nl))
-   **Veterinary and Comparative Pharmacology (VCP) representative:** André Joubert ([a.j.joubert\@uu.nl](mailto:a.j.joubert@uu.nl))

Other expertise:

-   **GIS specialists**: Lloyd Roga, Carmel Suchard
-   **Data solution architect and application specialist**: Adam El Kassimi
:::

## UU RDM Support team

In addition to the data management team at IRAS, the UU’s [Research Data Management (RDM) Support team](https://www.uu.nl/en/research/research-data-management) is there to support, advise and assist all researchers at UU with data management, data analysis, research software and code. A multidisciplinary network of data experts, software specialists and research engineers offer their expertise through training, tools, infrastructure, consultancy, and custom-made solutions at every stage of a research project. The support they provide complies with the FAIR principles: findable, accessible, interoperable and reusable. That way, it contributes to Open Science.

::: callout-note
### RDM Support workshops and guides

To learn more about how to manage your research data and software, the UU’s RDM Support team offers several trainings and workshops, as well as walk-in events. For a complete event agenda, together with information on trainings and workshop, please refer to the [RDM Support website](https://www.uu.nl/en/research/research-data-management/workshops).

[Reading guides](https://www.uu.nl/en/research/research-data-management/guides) on diverse RDM topics can also be found on the RDM Support website. The same goes for [tools](https://www.uu.nl/en/research/research-data-management/tools-services) that may be useful.
:::

## Other support services

Besides the IRAS Data Management team and RDM Support team, the following support services exist at UU:

-   [Research Support Office (RSO)](https://intranet.uu.nl/en/knowledgebase/research-support-office-veterinary-medicine?check_logged_in=1) of the Faculty of Veterinary Medicine: each faculty has an RSO. The RSO supports researchers throughout the year in the entire process of acquiring grants. For example: advice, information, reading, examples, budget assistance, data management, ethical questions, administrative data, etc.

-   [Privacy Officers](https://intranet.uu.nl/en/knowledgebase/team-research-data-management-and-privacy?check_logged_in=1) of the Faculty of Veterinary Medicine: if you are starting a new project or research involving the use of personal data, exchanging data with a third party, or have questions about the secure storage of data or GDPR, please contact the Privacy Officers. You could also contact them for questions about the safe and responsible use of AI.

## Contact

In case you have questions about research data management, please reach out!

::: callout-note
### Contact details

IRAS Data Management team: see @sec-intro_support_iras

RDM Support team: [info.rdm\@uu.nl](mailto:info.rdm@uu.nl)

RSO of the Faculty of Veterinary Medicine: [rso-dgk\@uu.nl](mailto:rso-dgk@uu.nl)

Privacy Officers of the Faculty of Veterinary Medicine: [privacy-dgk\@uu.nl](mailto:privacy-dgk@uu.nl)
:::

<!--# De IRAS-DM mailbox is inmiddels aangemaakt. We moeten nog wel een procedure bedenken hoe we de NPM gaan bijhouden. -->
