# Responsibilities {#sec-intro_responsibilities}

The UU distinguishes between different individuals or (groups of) actors, each bearing specific responsibilities for research data management. Specific responsibilities are outlined in the [UU's University Policy Framework for Research Data](https://www.uu.nl/sites/default/files/university_policy_framework_for_research_data_utrecht_university_-_january_2016.pdf). Here below, we’ve outlined our own additional specifications for research data management at IRAS.

::: callout-important
Please note that the [UU’s University Policy Framework for Research Data](https://www.uu.nl/sites/default/files/university_policy_framework_for_research_data_utrecht_university_-_january_2016.pdf) dates back to 1 January 2016. This is before e.g. the GDPR was established. Hence, some of the information mentioned in the policy framework is not up to date. UU is in the process of creating a new policy framework. In the meantime, please consult [RDM Support](mailto:info.rdm@uu.nl) in case of doubt about the information in the current policy framework.
:::

## Project leader

The **project leader** (e.g. principal investigator) is the main person responsible for:

-   Ensuring that all project members (see below) abide by the [UU's University Policy Framework for Research Data](https://www.uu.nl/sites/default/files/university_policy_framework_for_research_data_utrecht_university_-_january_2016.pdf), the [Research Data Management Guidelines of the Faculty of Veterinary Medicine](https://solisservices.sharepoint.com/:b:/s/WerkgroepRDM/IQCjzf0aKi-uS7x3TiG66yMoAWXuSrgG5IFlhtxLPUBkokE?e=5vHGXI&xsdata=MDV8MDJ8bS5rbmlqZmZAdXUubmx8NzYzM2EzZmQ2OGRlNGRmNDkxN2YwOGRlOTYyZTVkNmR8ZDcyNzU4YTBhNDQ2NGUwZmEwYWE0YmY5NWE0YTEwZTd8MHwwfDYzOTExMzMyMzAzMTUxMzczNnxVbmtub3dufFRXRnBiR1pzYjNkOGV5SkZiWEIwZVUxaGNHa2lPblJ5ZFdVc0lsWWlPaUl3TGpBdU1EQXdNQ0lzSWxBaU9pSlhhVzR6TWlJc0lrRk9Jam9pVFdGcGJDSXNJbGRVSWpveWZRPT18MHx8fA%3d%3d&sdata=eEh1c1o2WnBNZkJlQUQwL2JNSktjTVZBcWo0VVQ1VDNkd1lpYTdNZXRMWT0%3d) and the IRAS Research Data Management Guidelines (i.e. this document).

-   Organizing proper handling of research data.

-   Making sure that research data is stored and preserved in a sustainable manner after the research project has ended.

-   Keeping track of what type of identifying personal data will be collected and ensuring that the confidentiality is guaranteed through a detailed description of how identifying personal data will be handled, e.g. in a privacy statement or privacy regulations document. An example of a privacy statement can be found here: [https://obokids.nl/privacy-2/](https://obokids.nl/privacy-2/). The description can be kept fairly simple and general if the identifying personal data is kept in the central directory, but may need to be more elaborate and specific when an alternative is wanted or needed.

## Project members

Depending on their role and the project requirements, **project members** (e.g. students, researchers, research leaders, research assistants, data managers, project managers, etc.) have certain responsibilities as well. The creators of the data (researchers, students and their supervisors) have primary responsibility for good stewardship of their research data. For students, it is the responsibility of the thesis supervisor to ensure that research data is stored and preserved in a sustainable manner after the project has ended.

More specifically, project members should:

-   Familiarize themselves with the [UU's University Policy Framework for Research Data](https://www.uu.nl/sites/default/files/university_policy_framework_for_research_data_utrecht_university_-_january_2016.pdf), the [Research Data Management Guidelines of the Faculty of Veterinary Medicine](https://solisservices.sharepoint.com/:b:/s/WerkgroepRDM/IQCjzf0aKi-uS7x3TiG66yMoAWXuSrgG5IFlhtxLPUBkokE?e=5vHGXI&xsdata=MDV8MDJ8bS5rbmlqZmZAdXUubmx8NzYzM2EzZmQ2OGRlNGRmNDkxN2YwOGRlOTYyZTVkNmR8ZDcyNzU4YTBhNDQ2NGUwZmEwYWE0YmY5NWE0YTEwZTd8MHwwfDYzOTExMzMyMzAzMTUxMzczNnxVbmtub3dufFRXRnBiR1pzYjNkOGV5SkZiWEIwZVUxaGNHa2lPblJ5ZFdVc0lsWWlPaUl3TGpBdU1EQXdNQ0lzSWxBaU9pSlhhVzR6TWlJc0lrRk9Jam9pVFdGcGJDSXNJbGRVSWpveWZRPT18MHx8fA%3d%3d&sdata=eEh1c1o2WnBNZkJlQUQwL2JNSktjTVZBcWo0VVQ1VDNkd1lpYTdNZXRMWT0%3d) and the IRAS Research Data Management Guidelines (i.e. this document).

-   Sign the IRAS Identifying Personal Data Confidentiality Agreement in case the project requires working with personal data (see Appendix X<!--# T.z.t. als te downloaden bestand aan Quarto toevoegen, maar moet eerst geüpdaet worden, Inka gaat daarnaar kijken. Aftekenen van formulier moet bij DM-afgevaardigden belegd worden. -->).

-   Draw up proper procedures and design processes for the collection, storage, use, reuse, availability and long-term archiving of and provision of access to research data within the research project. The best way to do this is by developing a Data Management Plan (see @sec-planning_dmp) based on the information available in these guidelines.

-   Factor in the costs for the preservation and management of the research data and how they will be covered (institute-, subsidiary-funding or otherwise) (see @sec-planning_costs).

-   In the case of external data, agreements must be made with the provider of the external data. If participating in a joint study or research project agreements on data management should be made and recorded.

-   Ensure that the integrity, confidentiality and protection of the data are guaranteed (see [Data security and privacy](privacy.qmd)).

-   Make sure that research using personal data (which is the case for most research projects at IRAS) is conducted according to the [General Data Protection Regulation (GDPR, in Dutch: AVG)](https://gdpr.eu/tag/gdpr/). Other laws, such as the [Wet Medisch wetenschappelijk Onderzoek (WMO)](https://wetten.overheid.nl/BWBR0009408/2021-07-01) and  [Wet Geneeskundige Behandelingsovereenkomst (WGBO)](https://wetten.overheid.nl/BWBR0007021/2006-02-01), apply alongside it, filling in specific gaps or adding stricter rules in certain areas. In addition, there are specialized codes of conduct for handling personal data in research, for example the [COREON Code of Conduct for Health Research](https://www.coreon.org/wp-content/uploads/2023/06/Code-of-Conduct-for-Health-Research-2022.pdf). For more information, see the [RDM Support page](https://www.uu.nl/en/research/research-data-management/guides/policies-codes-of-conduct-and-laws) on policies, codes of conduct and laws and [Data security and privacy](privacy.qmd).

-   Make arrangements for the continued operational management of the research data after the end of the research project or termination of the employment contract at the institution.

An extended version on research data management responsibilities can be found in the [UU's University Policy Framework for Research Data](https://www.uu.nl/sites/default/files/university_policy_framework_for_research_data_utrecht_university_-_january_2016.pdf).
