# Data management plan (DMP) {#sec-planning_dmp}

RDM Support has instructions for [developing a DMP](https://www.uu.nl/en/research/research-data-management/guides/data-management-planning). At this page several questions about DMPs are answered, such as the ones below.

::: callout-note
## Questions and answers

-   **What is a DMP?** A DMP is a formal document you develop at the start of your research project which outlines all aspects of managing your data, both during and after your project.

-   **Why do you need a DMP?** Data management is all about making your work efficient and creating more value for your data for yourself and others, during and after your research, for instance by working towards [FAIR](https://www.uu.nl/en/node/81201) (findable, accessible, interoperable, reusable) data.

-   **How to write a data management paragraph for a grant proposal?** When writing a research grant proposal, funders, such as NWO, will often ask for a data management paragraph.

-   **How to write a DMP?** When writing your own DMP, you can:

    -   [Use DMPonline to write your DMP:]{.underline} DMPonline contains templates from many different funders (e.g., NWO, ZonMw and ERC) as well as the institutional templates from participating universities. The template offered by Utrecht University is tailored to the requirements which are laid down in the [University Policy Framework for Research Data](https://www.uu.nl/sites/default/files/university_policy_framework_for_research_data_utrecht_university_-_january_2016.pdf) And approved by both NWO and ZonMw.

    -   [Get advice or feedback:]{.underline} if you are in need of advice or [want your DMP reviewed](https://www.uu.nl/en/research/research-data-management/tools-services/data-management-plan-review), you can contact Research Data Management Support anytime, or click “Request feedback” in DMPonline.

    -   [Need more information or an introduction?]{.underline} Follow the online training [Learn to write your DMP](https://www.uu.nl/en/node/75857) or join the workshop [Quick start to Research Data Management](https://www.uu.nl/en/research/research-data-management/training-workshops/quick-start-to-research-data-management) and ask all your questions.
:::

The use of DMPonline is further explained at [this page](https://www.uu.nl/en/research/research-data-management/tools-services/tool-to-create-your-dmp-online).

## Our recommendation

Our recommendation is to write a DMP at the start of your research project and use the applicable template in DMPonline. This contains several examples you can use for your project. You can also find an example of a DMP developed for a research project at IRAS here: [**DMP OBO2 WP6 06102025.pdf**](doc/DMP%20OBO2%20WP6%2006102025.pdf).

If you have any questions or want to have your DMP reviewed, please contact [RDM Support](info.rdm@uu.nl) as outlined above. During onboarding this will be explained to new staff.
